import javafx.beans.property.adapter.JavaBeanObjectProperty;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;

public class Register extends javax.swing.JFrame {

    private int resultFlag;           //服务器返回的注册状态
    private Login login;

    public void setResultFlag(int resultFlag) {
        this.resultFlag = resultFlag;
    }

    /**
     * Creates new form Register
     */
    public Register(Login login) {
        this.login = login;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new JPanel();
        userNameLabel = new javax.swing.JLabel();
        userNameText = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordText = new JPasswordField();
        repasswordLabel = new javax.swing.JLabel();
        repasswordText = new JPasswordField();
        registerButton = new javax.swing.JButton();
        userNameErrorLabel = new javax.swing.JLabel();
        passwordErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "请输入注册信息", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18))); // NOI18N

        userNameLabel.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        userNameLabel.setText("用户名：");

        registerButton.addActionListener(new java.awt.event.ActionListener() {  //监听按钮事件
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });


        passwordLabel.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        passwordLabel.setText("密码：");

        repasswordLabel.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        repasswordLabel.setText("确认密码：");

        registerButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        registerButton.setText("注册");

        userNameErrorLabel.setVisible(false);
        userNameErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        userNameErrorLabel.setText("用户名为空！");

        passwordErrorLabel.setVisible(false);
        passwordErrorLabel.setForeground(new java.awt.Color(255, 0, 51));
        passwordErrorLabel.setText("密码不一致！");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(94, 94, 94)
                                                .addComponent(userNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(70, 70, 70)
                                                                .addComponent(repasswordLabel))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(passwordLabel)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(registerButton)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(passwordText, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                                                .addComponent(repasswordText)))))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(passwordErrorLabel)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(userNameErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 31, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userNameLabel)
                                        .addComponent(userNameErrorLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLabel)
                                        .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordErrorLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(repasswordLabel)
                                        .addComponent(repasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(registerButton)
                                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(75, Short.MAX_VALUE))
        );
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((dim.width - 608) / 2, (dim.height - 426) / 2);
        addWindowListener(new WindowAdapter() {    //监听当窗口关闭时的事件
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                login.setVisible(true);
            }
        });
        pack();

    }// </editor-fold>


    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {   //注册按钮监听函数
        // TODO add your handling code here:
        if (userNameText.getText().equals(""))
            userNameErrorLabel.setVisible(true);

        if (passwordText.getText().equals(""))
            passwordErrorLabel.setVisible(true);

        if (!userNameErrorLabel.isVisible() && !passwordErrorLabel.isVisible()) {    //此处将用户名和密码传至服务器
            ClientThread clientThread = null;
            try {
                clientThread = new ClientThread(InetAddress.getLocalHost(), 5500, new UserInfo(userNameText.getText(), passwordText.getText(), 2));
                clientThread.run();
                resultFlag = clientThread.getResultFlag();
                if (resultFlag == 1) {
                    JOptionPane.showMessageDialog(this, "注册成功！");
                    dispose();
                    new Login();
                } else if (resultFlag == 2)
                    JOptionPane.showMessageDialog(this, "注册失败！");
            } catch (UnknownHostException e) {
                System.out.println("获取本机IP失败！");
            } catch (IOException e) {
                System.out.println("客户端线程IO错误！");
            }
        }
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify                     
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passwordErrorLabel;
    private javax.swing.JLabel passwordLabel;
    private JPasswordField passwordText;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel repasswordLabel;
    private JPasswordField repasswordText;
    private javax.swing.JLabel userNameErrorLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameText;
    // End of variables declaration

}
